const styles = [
	'70s Psychedelic Poster',
	'80s Comic Book Art',
	'90s Grunge Graphic',
	'Afrofuturism Vision',
	'Acrylic',
	'Andy Warhol',
	'Art Deco Luxe',
	'Art Nouveau Flourish',
	'Barbiecore Glam Pop',
	'Baroque oil painting',
	'Biopunk Mutation',
	'Brutalist Poster Design',
	'Cartoon Astronaut',
	'Charcoal Drawing',
	'Cel-Shaded Anime',
	'Chuck Close',
	'Chrome Techno Armor',
	'Cinematic',
	'Classic Comic Strip',
	'Classic Fantasy Painting',
	'Collage Surrealism',
	'Comic Book',
	'Cubist Interpretation',
	'Cyber Samurai Portrait',
	'Cyberpunk Portrait',
	'Dark Fantasy Concept Art',
	'Dieselpunk Grunge',
	'Digital Illustration',
	'Disney Character',
	'Dreamcore Vibes',
	'Dreamlike Double Exposure',
	'Dramatic Baroque Style',
	'Early 2000s Pop Graphics',
	'Ethereal Fairy World',
	'Expressionist Brush Chaos',
	'Fantasy Oil Painting',
	'Futuristic Hologram',
	'Fantasy art',
	'Film Noir',
	'Glitchcore Distortion',
	'Glitch Vaporwave',
	'Golden Age Comic Strip',
	'Graffiti Street Art',
	'Haunted Vintage Photo',
	'Hypercolor Streetwear',
	'Hyperreal 3D Render',
	'Impressionist Brush Strokes',
	'Ink & Bone Gothic Fantasy',
	'Ink and Wash Drawing',
	'Ink Comic',
	'Line art Illustration',
	'Low-Poly 3D Render',
	'Manga Character',
	'Modern Minimalist',
	'Moebius Line Fantasy',
	'Moody Film',
	'Metal',
	'Mughal Miniature Painting',
	'Mythic Tarot Card',
	'Mythical Creature Transformation',
	'Neon Punk',
	'Neon-lit Synthwave',
	'Painting',
	'Papercut Layered Illustration',
	'Photographic',
	'Photorealistic Render',
	'Picasso',
	'Pirate',
	'Pixar-style 3D Character',
	'Pixel Art 8-Bit',
	'Pencil Sketch',
	'Pop Art Portrait',
	'Post-apocalyptic Wasteland',
	'Realistic',
	'Rembrandt',
	'Renaissance Portrait',
	'Retro',
	'Retro Pixel Portrait',
	'Retro Sci-Fi Pulp Cover',
	'Stunning',
	'Steampunk Gear-Laden Design',
	'Studio Ghibli Character',
	'Surreal Dreamscape',
	'Urban',
	'Van Gogh Style',
	'Vaporwave Aesthetic',
	'Vintage Newspaper Print',
	'Watercolor Painting',
	'Wireframe Mesh Render',
	'Zbrush Sculpt Render'
];

const fofrStyles = [
	'3D',
	'Emoji',
	'Video game',
	'Pixels',
	'Clay',
	'Toy'
];

module.exports = {
	styles,
	fofrStyles
};